location             = "southcentralus"
region               = "USSC"
appName              = "appServicePerf"
environment          = "DEV"
azureAdAdminObjectId = "3be33e46-bfe9-4d4c-b73f-be7d313fae27"