location             = "southcentralus"
region               = "USSC"
appName              = "appServicePerf"
environment          = "DEV"
azureAdAdminObjectId = "f4185ad1-cff5-4ec8-a96a-a1e1f7061bb6"