LOCATION             = "southcentralus"
REGION               = "USSC"
APPNAME              = "appServicePerf"
ENVIRONMENT          = "DEV"
AZUREADADMINOBJECTID = "3be33e46-bfe9-4d4c-b73f-be7d313fae27"