# This is a basic workflow that is manually triggered

name: Cleanup workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Package Versions
      uses: actions/delete-package-versions@v1.0.3
      with:
        package-name: 'artifact'
        num-old-versions-to-delete: 10
