variables:
  prodEnvironmentName: prod
  prodKeyVaultName: kvappServicePerfUSSCPROD
  prodResourceGroupName: rg-appServicePerf-USSC-PROD
  prodAppServiceSubnetName: appServiceSubnet
  prodvNetName: vnet-appServicePerf-USSC-PROD